before_install:
   - sudo apt-get update
install:
#   - sudo apt-get install -f
#   - sudo apt-get install -y texlive-latex-base 
#   - sudo apt-get install -y texlive-latex-recommended texlive-latex-extra
#   - sudo apt-get install -y texlive-science 
#   - sudo apt-get install -y texlive-fonts-recommended texlive-fonts-extra
#   - sudo apt-get install -y psutils
   - sudo apt-get install ghostscript
   - sudo apt-get install texlive-full
   - sudo apt-get install texlive-xetex
   - sudo apt-get install biber
   - sudo apt-get install latexmk
#   - curl -L https://github.com/holgern/travis-texlive/releases/download/2017-09-18_02/texlive.tar.xz | tar -JxC ~
   - PATH=$HOME/texlive/bin/x86_64-linux:$PATH
script:
   - make clean
   - make BUILD_STRATEGY=xelatex
   - make clean
   - make
